# Site settings
title:          Hansol's Blog
description:    "Hansol's blog"
url:            "https://giantsol.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Hansol Lee
  url:          https://giantsol.github.io
  email:        giantsol64@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
pagination:
  enabled: true
  per_page: 4
  title: 'Home'
